FROM python:3.11-slim

# Set working dir
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy app code
COPY . .

# Create upload folder
RUN mkdir -p /tmp/uploads

# Expose port
EXPOSE 5000

# Start Flask via Gunicorn
CMD ["gunicorn", "app:app", "--bind", "0.0.0.0:5000"]
